<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<!-- NuGet Package Info -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Finly.Shared.Contracts</PackageId>
		<Authors>Jason Spaninks</Authors>
		<Company>Finly</Company>
		<Description>Shared contracts for finly microservices.</Description>
		<RepositoryUrl>https://github.com/Finly-app/SharedContracts</RepositoryUrl>
		<!--<PackageReadmeFile>README.md</PackageReadmeFile>-->
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Confluent.Kafka" Version="2.10.0" />
	</ItemGroup>

</Project>
