<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<!-- NuGet Package Info -->
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>Finly.Shared.Contracts</PackageId>
		<Version>1.0.1</Version>
		<!-- You can also automate this -->
		<Authors>Jason Spaninks</Authors>
		<Company>Finly</Company>
		<Description>Shared contracts for finly microservices.</Description>
		<RepositoryUrl>https://github.com/Finly-app/SharedContracts</RepositoryUrl>
	</PropertyGroup>

</Project>
