name: Build and Upload package to NuGet (GitHub Packages)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore

      - run: dotnet build --no-restore --configuration Release

      - name: Generate version number
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack the NuGet package
        run: |
          dotnet pack ./Shared.Contracts/Shared.Contracts.csproj \
            -c Release \
            -p:PackageVersion=${{ env.PACKAGE_VERSION }} \
            --output ./nupkg

      - name: Push to NuGet.org
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
